### ISSUE TITLE
funding research projects: datasets

### ISSUE THREAD

**Issue by pdurbin** [good-labs/FUNDING.md#3]
I've been thinking a bit about how research projects are funded. There are examples of conflicts of interest, right? When you read the paper or look at the data, you're potentially interested in who funded the research, right? I just googled for "tobacco companies funding research" and came across "Tobacco industry manipulation of research" at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1497700/ which is probably a decent example. Here's the first figure about how the first strategy is "Fund research that supports the interest group position."

<img width="362" alt="Screen Shot 2019-05-03 at 5 54 28 PM" src="https://user-images.githubusercontent.com/21006/57167683-9f026100-6dcc-11e9-8aa3-ccb5b186c5f3.png">

In the context of a dataset, I know that https://schema.org/Dataset supports "funder" because I wrote a test for it at https://github.com/IQSS/dataverse/blame/v4.13/src/test/java/edu/harvard/iq/dataverse/export/SchemaDotOrgExporterTest.java#L329 😄 

I know way less about papers. 🤔 

I'm not sure where I'm going with this issue but I could probably find a dataset using the "funder" field in Schema.org JSON-LD if that's helpful.

**Comment by vsoch** [comment]
I'm a big fan of schema.org - I've created some tooling around exporting Dataset metadata for GitHub pages, etc. It would be great if you want to find an example of a Dataset json-ld - we can link from the org! I would start [searching](https://toolbox.google.com/datasetsearch) and my money is on if you find some academic / government dataset, it's more likely to declare funding.

**Comment by vsoch** [comment]
> I'm not sure where I'm going with this issue but I could probably find a dataset using the "funder" field in Schema.org JSON-LD if that's helpful.

Go for it!

**Comment by pdurbin** [comment]
@vsoch looks like you added one in 3183984 so I think I'm going to re-title this issue to be about datasets so we can close it. Maybe someone will come along who knows more about declaring funding in papers.

**Comment by vsoch** [comment]
I think funding in papers would be journal specific. It's better (or maybe cleaner) to start with the code that is used in the paper. I'm not sure a paper (without some kind of open source artifact) would fit into the bucket we are talking about.
